"""add_location_preferences_matching_batch

Revision ID: 551c0b7ca484
Revises: a54fb37b8d43
Create Date: 2026-03-22 18:03:32.577155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '551c0b7ca484'
down_revision: Union[str, None] = 'a54fb37b8d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matching_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity', sa.String(length=100), nullable=False),
    sa.Column('time_slot_date', sa.Date(), nullable=False),
    sa.Column('time_slot_hours', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('center_lng', sa.Float(), nullable=True),
    sa.Column('ai_score_payload', sa.JSON(), nullable=True),
    sa.Column('ai_model_used', sa.String(length=50), nullable=True),
    sa.Column('ai_tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposed_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('activity', sa.String(length=100), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ai_compatibility_score', sa.Float(), nullable=False),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['matching_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposed_group_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposed_group_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date_request_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['date_request_id'], ['date_requests.id'], ),
    sa.ForeignKeyConstraint(['proposed_group_id'], ['proposed_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('availability_slots', sa.Column('time_hours', sa.JSON(), nullable=False, server_default='[]'))
    # Backfill existing slots: convert time_window to time_hours
    op.execute("""
        UPDATE availability_slots SET time_hours =
            CASE time_window
                WHEN 'morning' THEN '[8,9,10,11]'::json
                WHEN 'afternoon' THEN '[12,13,14,15,16,17]'::json
                WHEN 'evening' THEN '[18,19,20,21]'::json
                WHEN 'night' THEN '[22,23,0,1]'::json
                ELSE '[18,19,20,21]'::json
            END
        WHERE time_window IS NOT NULL
    """)
    op.alter_column('availability_slots', 'time_window',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('location_updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('preferred_max_distance_km', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('body_type', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('height_cm', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('style_tags', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('users', sa.Column('pref_body_type', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('users', sa.Column('pref_height_range', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('users', sa.Column('pref_style', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('users', sa.Column('pref_social_energy_range', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('users', sa.Column('pref_humor_styles', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('users', sa.Column('pref_communication', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pref_communication')
    op.drop_column('users', 'pref_humor_styles')
    op.drop_column('users', 'pref_social_energy_range')
    op.drop_column('users', 'pref_style')
    op.drop_column('users', 'pref_height_range')
    op.drop_column('users', 'pref_body_type')
    op.drop_column('users', 'style_tags')
    op.drop_column('users', 'height_cm')
    op.drop_column('users', 'body_type')
    op.drop_column('users', 'preferred_max_distance_km')
    op.drop_column('users', 'location_updated_at')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.alter_column('availability_slots', 'time_window',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('availability_slots', 'time_hours')
    op.drop_table('proposed_group_members')
    op.drop_table('proposed_groups')
    op.drop_table('matching_batches')
    # ### end Alembic commands ###
