"""add friendships templates friend_code

Revision ID: 90a8c94251b9
Revises: a4d3adb5e01b
Create Date: 2026-03-22 15:26:36.547558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a8c94251b9'
down_revision: Union[str, None] = 'a4d3adb5e01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_request_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('activities', sa.JSON(), nullable=False),
    sa.Column('group_size', sa.Integer(), nullable=False),
    sa.Column('friend_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('friend_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Add friend_code as nullable first, fill existing rows, then make non-null
    op.add_column('users', sa.Column('friend_code', sa.String(length=6), nullable=True))

    # Generate unique friend codes for existing users
    from sqlalchemy import text
    conn = op.get_bind()
    users = conn.execute(text("SELECT id FROM users WHERE friend_code IS NULL")).fetchall()
    import random, string
    used_codes = set()
    for row in users:
        while True:
            code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
            if code not in used_codes:
                used_codes.add(code)
                break
        conn.execute(text("UPDATE users SET friend_code = :code WHERE id = :uid"), {"code": code, "uid": row[0]})

    op.alter_column('users', 'friend_code', nullable=False)
    op.create_unique_constraint('uq_users_friend_code', 'users', ['friend_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'friend_code')
    op.drop_table('friendships')
    op.drop_table('date_request_templates')
    # ### end Alembic commands ###
