"""add onboarding personality lifestyle fields

Revision ID: a4d3adb5e01b
Revises: 001
Create Date: 2026-03-22 14:03:07.573471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d3adb5e01b'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('date_groups', 'venue_address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('reports', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('reports', 'admin_notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('users', sa.Column('prompts', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('users', sa.Column('selfie_status', sa.String(length=20), nullable=False, server_default='none'))
    op.add_column('users', sa.Column('selfie_urls', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('users', sa.Column('onboarding_path', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('relationship_intent', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('social_energy', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('humor_styles', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('users', sa.Column('communication_pref', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('conflict_style', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('drinking', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('smoking', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('exercise', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('diet', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('sleep_schedule', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('group_role', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('users', sa.Column('ideal_group_size', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('dealbreakers', sa.JSON(), nullable=False, server_default='[]'))
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('users', 'dealbreakers')
    op.drop_column('users', 'ideal_group_size')
    op.drop_column('users', 'group_role')
    op.drop_column('users', 'sleep_schedule')
    op.drop_column('users', 'diet')
    op.drop_column('users', 'exercise')
    op.drop_column('users', 'smoking')
    op.drop_column('users', 'drinking')
    op.drop_column('users', 'conflict_style')
    op.drop_column('users', 'communication_pref')
    op.drop_column('users', 'humor_styles')
    op.drop_column('users', 'social_energy')
    op.drop_column('users', 'relationship_intent')
    op.drop_column('users', 'onboarding_path')
    op.drop_column('users', 'selfie_urls')
    op.drop_column('users', 'selfie_status')
    op.drop_column('users', 'prompts')
    op.alter_column('reports', 'admin_notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reports', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('date_groups', 'venue_address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
