"""add_push_token_to_users

Revision ID: a54fb37b8d43
Revises: 718d732c24d3
Create Date: 2026-03-22 17:23:40.241005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54fb37b8d43'
down_revision: Union[str, None] = '718d732c24d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('push_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'push_token')
    # ### end Alembic commands ###
